logging.level:
  org.springframework.security: TRACE

spring:
  docker:
    compose:
      file: classpath:docker/compose.yml
      readiness:
        wait: never
  security:
    filter:
      dispatcher-types: async, error, request, forward
    saml2:
      relyingparty:
        registration:
          one:
            entity-id: "{baseUrl}/saml/metadata"
            signing.credentials:
              - private-key-location: classpath:credentials/rp-private.key
                certificate-location: classpath:credentials/rp-certificate.crt
            assertingparty.metadata-uri: http://idp-one.7f000001.nip.io/simplesaml/saml2/idp/metadata.php
            singlelogout:
              binding: REDIRECT
              url: "{baseUrl}/saml/logout"
              responseUrl: "{baseUrl}/saml/SingleLogout"
            acs:
              location: "{baseUrl}/saml/SSO"
